# Generated by Django 5.0.6 on 2024-10-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameInfo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
